### PR TITLE
Adds PSBT tests

### PR DESCRIPTION
**Pull request by hodlwave**
This PR should be a bit more controversial as it makes several changes to the actual `psbt` library.

Notes on the changes:
* Updates various dictionaries to collections::OrderedDict to remove non-determinism
when a psbt is parsed and then serialized; this isn't strictly necessary for BIP174,
but it makes it more straightforward to use the BIP174 test vectors for testing.
* Explicitly validate key sizes for keys that are always 1 byte long; this prevents
these keys from being parsed as unknown fields and enables the class to meet the BIP174
test vectors.
* Adds a test to ensure `PSBT::sign_with` generates the expected signatures using
the signer test vector in BIP174; since, this test vector necessitates the signing of
a segwit AND legacy input, I added a line of code to enable legacy signing.

Let me know what you think!

### CODE REVIEW

**Comment by stepansnigirev** [comment]
Awesome, thanks! Merged!

**Comment by stepansnigirev** [comment]
One change that I made after merging this:
https://github.com/diybitcoinhardware/f469-disco/commit/946bd98a459896b76fdb6a0eb7b59ac14d197734

tx in psbt transaction doesn't have any information that would help to determine if it's segwit or not - it doesn't have a segwit marker, witness is empty etc.
So the best way to determine if the input should be signed as segwit or legacy is to check if there is witness_utxo is in psbt input.
witness_script is not None only if p2wsh is used.

Now I am thinking that witness_utxo may be missing as well if non_witness_utxo is provided, so to make sure it's segwit it's better to check that *one* of the following conditions is met:
- witness_utxo is in psbt input or
- prev output scriptpubkey is segwit (for native segwit) or
- redeem script is segwit (for nested segwit) or
- witness script is not empty (for p2wsh / p2sh-p2wsh)

**Comment by hodlwave** [comment]
That makes sense to me. Does this look right?
```
# detect if it is a segwit input
# tx.input[i] doesn't have any info about that in raw psbt
if (inp.witness_script is not None or
    inp.witness_utxo is not None or
    utxo.script_pubkey.script_type() in {'p2wpkh', 'p2wsh'} or
    (inp.redeem_script is not None and inp.redeem_script.script_type() in {'p2wpkh', 'p2wsh'})):
    h = self.tx.sighash_segwit(i, sc, value)
else:
    h = self.tx.sighash_legacy(i, sc)
```

**Comment by stepansnigirev** [comment]
Yes, looks correct, and `utxo` should be `inp.non_witness_utxo.vout[num_out]` where `num_out` is `self.tx.vin[i].vout`

**Pull request merged**
